<?php

namespace AccueilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosRepository extends EntityRepository {

    public function Annonces($id) {


        $qb = $this->createQueryBuilder('a');


        $qb->where('a.id = :id')
                ->setParameter('id', $id)
        ;

        // $genres contains all the genres and the associated movies
        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

}
