connexion_homepage:
    path:     /login
    defaults: { _controller: ConnexionBundle:Default:connexion }

Signup_homepage:
    path:     /signup
    defaults: { _controller: ConnexionBundle:Default:Signup }
    





