connexion_homepage:
    path:     /login
    defaults: { _controller: ConnexionBundle:Default:login }

Signup_homepage:
    path:     /signup
    defaults: { _controller: ConnexionBundle:Default:signup }
    
login_listContact:
    path:     /listContact
    defaults: { _controller: LoginLoginBundle:Default:listContact}
