connexion_homepage:
    path:     /login
    defaults: { _controller: ConnexionBundle:Default:login }

Signup_homepage:
    path:     /signup
    defaults: { _controller: ConnexionBundle:Default:signup }
    
login:
    path:     /connexion
    defaults: { _controller: ConnexionBundle:Default:connexionLoc}
    
loginPro:
    path:     /proprietaire
    defaults: { _controller: ConnexionBundle:Default:connexionProprietaire}
    
    

