connexion:
    resource: "@ConnexionBundle/Resources/config/routing.yml"
    prefix:   /

Signup:
    resource: "@ConnexionBundle/Resources/config/routing.yml"
    prefix:   /

accueil:
    resource: "@AccueilBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
