<?php

namespace AccueilBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AccueilBundle\Entity\Users;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository {

    public function getLoc($email) {


        $qb = $this->createQueryBuilder('a');
        
        $qb->select('a.locataire')
            ->where('a.email = :email')
            ->setParameter('email', $email);
           
        
        
        return $qb->getQuery()
                  ->getSingleResult();


        
    }
    
    public function getUser($id){
        
        $qb = $this->createQueryBuilder('a');
        
        $qb->select('a.email','a.mdp')
            ->where('a.id = :id')
            ->setParameter('id', $id);
           
        
        
        return $qb->getQuery()
                  ->getSingleResult();

        
    }

}
