accueil_homepage:
    path:     /accueil
    defaults: { _controller: AccueilBundle:Default:index }
    
localisation_homepage:
    path:     /localisation
    defaults: { _controller: AccueilBundle:Default:localisation }
    

location_homepage:
    path:     /location
    defaults: { _controller: AccueilBundle:Default:location }


contact_homepage:
    path:     /contact
    defaults: { _controller: AccueilBundle:Default:contact }
    
    
service_homepage:
    path:     /services
    defaults: { _controller: AccueilBundle:Default:service }