accueil_homepage:
    path:     /accueil
    defaults: { _controller: AccueilBundle:Default:index }
    
localisation_homepage:
    path:     /localisation
    defaults: { _controller: AccueilBundle:Default:localisation }
    

location_homepage:
    path:     /location
    defaults: { _controller: AccueilBundle:Default:location }
    

annonce_homepage:
    path:     /annonce
    defaults: { _controller: AccueilBundle:Default:annonce }
    
annonces_homepage:
    path:     /{id}/voir
    defaults: { _controller: AccueilBundle:Default:VoirAnnonce }
    requirements:
        id: \d+


contact_homepage:
    path:     /contact
    defaults: { _controller: AccueilBundle:Default:contact }
    
    
service_homepage:
    path:     /services
    defaults: { _controller: AccueilBundle:Default:service }